# Generated by Django 3.2 on 2021-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='access_ticket',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('Amistoso', 'Amistoso'), ('Torneo', 'Torneo'), ('Final', 'Final'), ('Internacional', 'Internacional')], default='Torneo', max_length=32),
        ),
    ]
