# Generated by Django 3.2 on 2021-05-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210519_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='local_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_teams', to='api.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='visiting_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_teams', to='api.team'),
        ),
    ]
