# Generated by Django 3.2 on 2021-05-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210519_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='team',
        ),
        migrations.AddField(
            model_name='users',
            name='asociation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_asociation', to='api.asociation'),
        ),
        migrations.AddField(
            model_name='users',
            name='athlete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_athlete', to='api.asociation'),
        ),
    ]
