# Generated by Django 3.2 on 2021-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_asociation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociation',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
