# Generated by Django 3.2.3 on 2021-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_asociation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=32)),
                ('news_preview', models.TextField(max_length=50)),
                ('news_description', models.TextField(max_length=500)),
            ],
        ),
    ]
