# Generated by Django 3.2.3 on 2021-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_description',
            field=models.TextField(max_length=1000),
        ),
    ]
