# Generated by Django 3.2.3 on 2021-06-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_team_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='category',
            new_name='tournament_category',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='country',
            new_name='tournament_country',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='name',
            new_name='tournament_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_logo',
        ),
        migrations.AddField(
            model_name='match',
            name='journey',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='match_parking',
            field=models.TextField(default='no', max_length=300),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to='api.team'),
        ),
    ]
