# Generated by Django 3.2.3 on 2021-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_users_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='shirt_number',
            field=models.IntegerField(default=99),
        ),
    ]
