# Generated by Django 3.2.3 on 2021-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_athlete_shirt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
