# Generated by Django 3.2.3 on 2021-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_athlete_asociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='access_ticket',
            field=models.FloatField(default=0),
        ),
    ]
