# Generated by Django 3.2.3 on 2021-06-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_match_access_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='local_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_teams', to='api.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='visiting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_teams', to='api.team'),
        ),
    ]
