# Generated by Django 3.2.3 on 2021-06-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210601_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='local_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='api.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='api.Team'),
        ),
    ]
