# Generated by Django 3.2.3 on 2021-06-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210604_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='api.athlete')),
                ('match_played', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
