# Generated by Django 3.2.3 on 2021-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210604_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='local_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='visiting_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
