# Generated by Django 3.2.3 on 2021-11-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210604_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to='api.team'),
        ),
    ]
