# Generated by Django 3.2.3 on 2021-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210604_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
